# frozen_string_literal: true

require "rubygems"
require "hoe"
require "rake/clean"

Hoe.plugin :halostatue
Hoe.plugin :minitest

Hoe.spec "app_identity" do
  developer("Austin Ziegler", "aziegler@kineticcommerce.com")
  developer("Kinetic Commerce", "dev@kineticcommerce.com")

  self.git_release_tag_prefix = "ruby-v"

  self.history_file = "Changelog.md"
  self.readme_file = "README.md"

  # This is a hack because of an issue with Hoe 3.26, but I'm not sure which
  # hoe version introduced this issue or if it's a JRuby issue. This issue is
  # demonstrable in lib/hoe.rb at line 676, which is (reformatted for space):
  #
  # ```ruby
  # readme =
  #   input
  #     .lines
  #     .chunk { |l| l[/^(?:=+|#+)/] || "" } # # chunk is different somehow
  #     .map(&:last) # <-- HERE: "#" does not respond to #last
  #     .each_slice(2)
  #     .map { |k, v|
  #       kp = k.join
  #       kp = kp.strip.chomp(":").split.last.downcase if k.size == 1
  #       [kp, v.join.strip]
  #     }
  #     .to_h
  # ```
  #
  # We don't *ship* with JRuby, but use it in CI only, so this is here at least
  # temporarily.
  if RUBY_PLATFORM.match?(/java/)
    self.summary = self.description = "Description for testing"
    self.homepage = "https://github.com/KineticCafe/app-identity/tree/main/ruby/"
  end

  license "Apache-2.0"

  require_ruby_version ">= 2.7", "< 4"

  spec_extras[:metadata] = ->(val) {
    val.merge!({
      "rubygems_mfa_required" => "true"
    })
  }

  extra_deps << ["optimist", "~> 3.0"]
  extra_deps << ["base64", "~> 0.1"]
  extra_deps << ["ostruct", "~> 0.6"]

  extra_dev_deps << ["appraisal", "~> 2.4"]
  extra_dev_deps << ["hoe", "~> 4.0"]
  extra_dev_deps << ["hoe-halostatue", "~> 1.0"]
  extra_dev_deps << ["minitest", "~> 5.16"]
  extra_dev_deps << ["minitest-autotest", "~> 1.0"]
  extra_dev_deps << ["minitest-bisect", "~> 1.2"]
  extra_dev_deps << ["minitest-focus", "~> 1.1"]
  extra_dev_deps << ["minitest-pretty_diff", "~> 0.1"]
  extra_dev_deps << ["rack-test", "~> 2.0"]
  extra_dev_deps << ["rake", ">= 10.0", "< 14"]
  extra_dev_deps << ["rdoc", "~> 6.4"]
  extra_dev_deps << ["standard", "~> 1.0"]
  extra_dev_deps << ["standard-minitest", "~> 1.0"]
  extra_dev_deps << ["standard-thread_safety", "~> 1.0"]
end

namespace :console do
  task :pry do
    exec "pry -Ilib -rapp_identity"
  end

  task :irb do
    exec "irb -Ilib -rapp_identity"
  end
end

desc "Open a console with AppIdentity loaded"
task console: "console:irb"
