D = Steep::Diagnostic

target :lib do
  signature "sig"

  check "lib"                       # Directory name
  ignore "lib/app_identity/rack_middleware.rb"
  # ignore "lib/app_identity/rack_middleware.rb", "lib/app_identity/faraday_middleware.rb"

  library "digest"
  library "rack"
  library "faraday"
  # library "pathname", "set"       # Standard libraries
  # library "strong_json"           # Gems

  # configure_code_diagnostics(D::Ruby.strict)       # `strict` diagnostics setting
  configure_code_diagnostics(D::Ruby.lenient)      # `lenient` diagnostics setting
  # configure_code_diagnostics do |hash|             # You can setup everything yourself
  #   hash[D::Ruby::NoMethod] = :information
  # end
end

# target :test do
#   signature "sig", "sig-private"

#   check "test"

#   # library "pathname", "set"       # Standard libraries
# end
