version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/node'
        versions: ["22.x.x"]
    commit-message:
      prefix: 'deps(ts)'

  - package-ecosystem: mix
    directory: /elixir
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(elixir)'

  - package-ecosystem: bundler
    directory: /ruby
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(ruby)'
