version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    groups:
      all:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/node'
        versions: ["22.x.x"]
    commit-message:
      prefix: 'deps(ts)'
    groups:
      all:
        update-types:
          - minor
          - patch

  - package-ecosystem: mix
    directory: /elixir
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(elixir)'
    groups:
      all:
        update-types:
          - minor
          - patch

  - package-ecosystem: bundler
    directory: /ruby
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(ruby)'
    groups:
      all:
        update-types:
          - minor
          - patch
