version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/node'
        versions: ["22.x.x"]

  - package-ecosystem: mix
    directory: /elixir
    schedule:
      interval: monthly

  - package-ecosystem: bundler
    directory: /ruby
    schedule:
      interval: monthly
