version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    cooldown:
      default-days: 7
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/node'
        update-types: [version-update:semver-major]
    commit-message:
      prefix: 'deps(ts)'
    cooldown:
      default-days: 7
    groups:
      npm:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: mix
    directory: /elixir
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(elixir)'
    cooldown:
      default-days: 7
    groups:
      mix:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: bundler
    directory: /ruby
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(ruby)'
    cooldown:
      default-days: 7
    groups:
      bundler:
        applies-to: version-updates
        update-types:
          - minor
          - patch
