blank_issues_enabled: true

contact_links:
  - name: Discussions
    url: https://github.com/KineticCafe/app_identity/discussions
    about: |
      Feature requests are encouraged to be discussed prior to submission in the
      issue tracker.
