class AppIdentity::Internal
  include AppIdentity::Validation
  self.@instance: AppIdentity::Internal

  def self.instance: -> AppIdentity::Internal
  def self.generate_proof!: (
      AppIdentity::App | untyped app,
      ?nonce: String?,
      ?version: Integer?,
      ?disallowed: (Set[Integer] | Array[Integer])?
    ) -> AppIdentity::proof?
  def self.parse_proof!: (String | AppIdentity::proof proof) -> AppIdentity::proof
  def self.verify_proof!: (
      String | AppIdentity::proof proof,
      (AppIdentity::App | untyped) app,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::App?

  def generate_proof!: (
      AppIdentity::App | untyped app,
      ?nonce: String?,
      ?version: Integer?,
      ?disallowed: (Set[Integer] | Array[Integer])?
    ) -> AppIdentity::proof?

  def parse_proof!: (String | AppIdentity::proof proof) -> AppIdentity::proof
  def verify_proof!: (
      AppIdentity::proof | String proof,
      (AppIdentity::App | untyped) app,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::App?

  private
  def __generate_proof: (
      AppIdentity::App app,
      String nonce, Integer version,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::proof?

  def __generate_padlock: (AppIdentity::App app, untyped nonce, Integer version) -> String
  def versions_compatible!: (Integer app_version, Integer version) -> void
  def valid_nonce!: (String? nonce, Integer version, untyped config) -> void
  def compare_padlocks: (String? generated, String? provided) -> bool
  def generate_version_nonce: (Integer version) -> String
end
