module AppIdentity::Versions
  self.@disalllowed: Set[Integer]

  def self.[]: (Integer version) -> Integer
  def self.valid?: (Integer version) -> bool
  def self.valid!: (Integer version) -> true
  def self.allowed?: (Integer version, ?(Set[Integer] | Array[Integer])? provided) -> bool
  def self.allowed!: (Integer version, ?(Set[Integer] | Array[Integer])? provided) -> true
  def self.disallow: (*untyped versions) -> Set[Integer]
  def self.allow: (*untyped versions) -> Set[Integer]
  def self.coerce_versions: (Array[Integer] versions) -> Array[Integer]
  def self.disallowed: -> Set[Integer]

  class Base
    self.@defined: Hash[untyped, (Base | RandomNonce | TimestampNonce | V1 | V2 | V3 | V4)]
    self.@_instance: (Base | RandomNonce | TimestampNonce | V1 | V2 | V3 | V4)

    def self.defined: -> Hash[untyped, untyped]
    def self.instance: -> (Base | RandomNonce | TimestampNonce | V1 | V2 | V3 | V4)
    def self.inherited: (singleton(RandomNonce) | singleton(TimestampNonce) | singleton(V1) | singleton(V2) | singleton(V3) | singleton(V4) subclass) -> void
    def make_digest: (untyped raw) -> untyped
    def inspect: -> String
    def check_nonce!: (untyped nonce, untyped _config) -> nil
    def self.version: -> Integer
  end

  class RandomNonce < Base
    def nonce_type: -> :random
    def generate_nonce: -> String
  end

  class TimestampNonce < Base
    def nonce_type: -> :timestamp
    def generate_nonce: -> String
    def check_nonce!: (untyped nonce, untyped config) -> nil

    private
    def config_fuzz: (AppIdentity::config) -> Integer
    def parse_timestamp!: (String nonce) -> Time
  end

  class V1 < RandomNonce
    def digest_algorithm: -> singleton(Digest::SHA256)
  end

  class V2 < TimestampNonce
    def digest_algorithm: -> singleton(Digest::SHA256)
  end

  class V3 < TimestampNonce
    def digest_algorithm: -> singleton(Digest::SHA384)
  end

  class V4 < TimestampNonce
    def digest_algorithm: -> singleton(Digest::SHA512)
  end
end
