class AppIdentity
  VERSION: String
  NAME: String
  SPEC_VERSION: Integer
  INFO: {name: String, version: String, spec_version: Integer}

  def self.generate_proof: (untyped app, ?nonce: nil, ?version: nil, ?disallowed: nil) -> nil
  def self.generate_proof!: (untyped app, ?nonce: nil, ?version: nil, ?disallowed: nil) -> untyped
  def self.parse_proof: (untyped proof) -> {version: Integer, id: String?, nonce: String?, padlock: String?}?
  def self.parse_proof!: (untyped proof) -> {version: Integer, id: String?, nonce: String?, padlock: String?}
  def self.verify_proof: (untyped proof, untyped app, ?disallowed: nil) -> nil
  def self.verify_proof!: (untyped proof, untyped app, ?disallowed: nil) -> untyped
  def self.disallow_version: (*untyped versions) -> Set[bot]
  def self.allow_version: (*untyped versions) -> Set[bot]
  def self.internal: -> AppIdentity::Internal
end
