class AppIdentity
  VERSION: String
  NAME: String
  SPEC_VERSION: Integer
  INFO: {name: String, version: String, spec_version: Integer}

  type config = {fuzz: Integer}
  type proof = {version: Integer, id: String, nonce: String, padlock: String}


  def self.generate_proof: (
      (AppIdentity::App | untyped) app,
      ?nonce: String?,
      ?version: Integer?,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::proof?
  def self.generate_proof!: (
      (AppIdentity::App | untyped) app,
      ?nonce: String?,
      ?version: Integer?,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::proof?
  def self.parse_proof: (String | proof proof) -> AppIdentity::proof?
  def self.parse_proof!: (String | proof proof) -> AppIdentity::proof
  def self.verify_proof: (
      String | proof proof,
      (AppIdentity::App | untyped) app,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::App?
  def self.verify_proof!: (
      String | proof proof,
      (AppIdentity::App | untyped) app,
      ?disallowed: (Set[Integer] | Array[Integer])?
  ) -> AppIdentity::App?
  def self.disallow_version: (*Integer versions) -> void
  def self.allow_version: (*Integer versions) -> void
  def self.internal: -> AppIdentity::Internal
end
