name: Check DCO

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - uses: KineticCafe/actions-dco@v1.3.2
        with:
          exempt-authors: |
            @kineticcommerce.com
            @kineticcafe.com
