name: Check DCO

on:
  pull_request:

permissions: {}

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: KineticCafe/actions-dco@6e1652ef3027ce128e65e6edd215ae053350bd16 # v2.1.1
