name: Check DCO

on:
  pull_request:

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: KineticCafe/actions-dco@416cafbc9c07f26219d09981d9ac49ce29b5bfea #v1.3.4
        with:
          exempt-authors: |
            @kineticcommerce.com
            @kineticcafe.com
