name: Dependabot auto-merge

on:
  pull_request:

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: KineticCafe/actions/dependabot-automerge@v2.0
        with:
          update-type: minor
          merge-type: rebase
