name: Dependabot auto-merge

on:
  pull_request:

jobs:
  dependabot-automerge:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: KineticCafe/actions/dependabot-automerge@e429bd61bc6c97f06832e02dfbc7aff3bff5381c #v2.0.1
        with:
          update-type: minor
          merge-type: rebase
