name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  elixir-ci:
    name: Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})

    strategy:
      fail-fast: true
      matrix:
        include:
          - elixir: '1.10'
            otp: '21'
          - elixir: '1.11'
            otp: '21'
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.12'
            otp: '24'
          - elixir: '1.13'
            otp: '24'
            check_formatted: true
            warnings_as_errors: true
            dialyzer: true
            credo: true
          - elixir: '1.14' # latest version
            otp: '25'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-elixir@v1
        id: install
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v2
        with:
          key: builds@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/deps
            elxir/_build

      - run: mix 'do' deps.get, deps.compile
        working-directory: ./elixir

      - run: mix format --check-formatted
        working-directory: ./elixir
        if: matrix.check_formatted

      - run: mix compile --warnings-as-errors
        working-directory: ./elixir
        if: matrix.warnings_as_errors

      - run: mix compile
        working-directory: ./elixir
        if: ${{ !matrix.warnings_as_errors }}

      - run: mix test
        working-directory: ./elixir

      - run: >
          mix app_identity generate --stdout |
          mix app_identity run --stdin --strict
        working-directory: ./elixir

      - run: mix credo --strict
        working-directory: ./elixir
        if: matrix.credo

      - uses: actions/cache@v2
        with:
          key: plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/priv/plts
          restore-keys: |
            plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-

      - run: mix dialyzer
        working-directory: ./elixir
        if: matrix.dialyzer
