name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  elixir-ci:
    name: Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})

    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.12'
            otp: '24'
            os: ubuntu-22.04
          - elixir: '1.13'
            otp: '24'
            os: ubuntu-22.04
          - elixir: '1.14'
            otp: '25'
            os: ubuntu-22.04
          - elixir: '1.15'
            otp: '26'
            os: ubuntu-22.04
          - elixir: '1.16'
            otp: '26'
            os: ubuntu-22.04
          - elixir: '1.17'
            otp: '27'
            os: ubuntu-22.04
          - elixir: '1.18'
            otp: '27'
            os: ubuntu-24.04
            check_formatted: true
            warnings_as_errors: true
            dialyzer: true
            credo: true
            # coveralls: true

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            builds.hex.pm:443
            coveralls.io:443
            github.com:443
            repo.hex.pm:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: install
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: builds@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/deps
            elxir/_build

      - run: mix 'do' deps.get, deps.compile
        working-directory: ./elixir

      - run: mix format --check-formatted
        working-directory: ./elixir
        if: matrix.check_formatted

      - run: mix compile --warnings-as-errors
        working-directory: ./elixir
        if: matrix.warnings_as_errors

      - run: mix compile
        working-directory: ./elixir
        if: ${{ !matrix.warnings_as_errors }}

      - run: mix coveralls.github
        working-directory: ./elixir
        if: ${{ matrix.coveralls }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: mix test
        if: ${{ !matrix.coveralls }}
        working-directory: ./elixir

      # Using MIX_QUIET=1 should work for this, except that with older versions
      # of Elixir and OTP (OTP 25 or earlier), there's a persistent truncation
      # of the output as the generator VM shuts down before stdout is complete
      # which is not exhibited with Mix shell write but is exhibited with IO
      # write.
      - run: |
          # mix app_identity generate --stdout |
          #   mix app_identity run --diagnostic --stdin --strict
          mix app_identity generate
          mix app_identity run --diagnostic --strict app-identity-suite-elixir.json
          rm -f app-identity-suite-elixir.json
        working-directory: ./elixir

      - run: mix credo --strict
        working-directory: ./elixir
        if: matrix.credo

      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          key: plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/priv/plts
          restore-keys: |
            plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-

      - run: mix dialyzer --format github
        working-directory: ./elixir
        if: matrix.dialyzer
