name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  elixir-ci:
    name: Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})

    permissions:
      contents: read

    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.12'
            otp: '24'
            os: ubuntu-22.04
          - elixir: '1.13'
            otp: '24'
            os: ubuntu-22.04
          - elixir: '1.14'
            otp: '25'
            os: ubuntu-22.04
          - elixir: '1.15'
            otp: '26'
            os: ubuntu-22.04
          - elixir: '1.16'
            otp: '26'
            os: ubuntu-22.04
          - elixir: '1.17'
            otp: '27'
            os: ubuntu-22.04
          - elixir: '1.18'
            otp: '27'
            os: ubuntu-24.04
            check_formatted: true
            warnings_as_errors: true
            dialyzer: true
            credo: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@75edbb82877ab10edeb12a99c3cf2f0909f3dc87 #v1.20.1
        id: install
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
        with:
          key: builds@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/deps
            elxir/_build

      - run: mix 'do' deps.get, deps.compile
        working-directory: ./elixir

      - run: mix format --check-formatted
        working-directory: ./elixir
        if: matrix.check_formatted

      - run: mix compile --warnings-as-errors
        working-directory: ./elixir
        if: matrix.warnings_as_errors

      - run: mix compile
        working-directory: ./elixir
        if: ${{ !matrix.warnings_as_errors }}

      - run: mix test
        working-directory: ./elixir

      # Using MIX_QUIET=1 should work for this, except that with older versions
      # of Elixir and OTP (OTP 25 or earlier), there's a persistent truncation
      # of the output as the generator VM shuts down before stdout is complete
      # which is not exhibited with Mix shell write but is exhibited with IO
      # write.
      - run: |
          # mix app_identity generate --stdout |
          #   mix app_identity run --diagnostic --stdin --strict
          mix app_identity generate
          mix app_identity run --diagnostic --strict app-identity-suite-elixir.json
          rm -f app-identity-suite-elixir.json
        working-directory: ./elixir

      - run: mix credo --strict
        working-directory: ./elixir
        if: matrix.credo

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
        with:
          key: plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            elixir/priv/plts
          restore-keys: |
            plts@elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-

      - run: mix dialyzer
        working-directory: ./elixir
        if: matrix.dialyzer
