name: Ruby CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruby-ci:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }} - ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        gemfile:
          - rack_1
          - rack_2
          - rack_3
        os:
          - ubuntu-20.04
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - head
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head
          - truffleruby+graalvm
          - truffleruby+graalvm-head
        include:
          - ruby: head
            continue-on-error: true
          - ruby: jruby-head
            continue-on-error: true
          - ruby: truffleruby-head
            continue-on-error: true
          - ruby: truffleruby+graalvm-head
            continue-on-error: true
          - os: ubuntu-22.04
            ruby: head
            gemfile: rack_2
            continue-on-error: true
          - os: ubuntu-22.04
            ruby: head
            continue-on-error: true
            gemfile: rack_3
          - os: ubuntu-22.04
            ruby: '3.1'
            gemfile: rack_2
          - os: ubuntu-22.04
            ruby: '3.1'
            gemfile: rack_3
          - os: ubuntu-22.04
            ruby: '3.2'
            gemfile: rack_2
          - os: ubuntu-22.04
            ruby: '3.2'
            gemfile: rack_3

    runs-on: ${{ matrix.os }}

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/gemfiles/${{ matrix.gemfile }}.gemfile

    continue-on-error: ${{ matrix.continue-on-error || false }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ./ruby

      - run: bundle exec ruby -S rake test --trace
        working-directory: ./ruby

      - run: bundle exec standardrb
        working-directory: ./ruby

      - run: >
          bundle exec bin/app-identity-suite-ruby generate --stdout |
          bundle exec bin/app-identity-suite-ruby run --stdin --strict
        working-directory: ./ruby
