name: Ruby CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: Ruby Lint
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 #v1.245.0
        with:
          ruby-version: '3.3'
          rubygems: latest
          bundler: 2
          bundler-cache: true
          working-directory: ./ruby

      - run: bundle exec standardrb
        working-directory: ./ruby

  required-ubuntu:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }} - ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rack_1
          - rack_2
          - rack_3
        os:
          - ubuntu-22.04
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - truffleruby

    runs-on: ${{ matrix.os }}

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 #v1.245.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ./ruby

      - run: bundle exec ruby -S rake test --trace
        working-directory: ./ruby

      - run: >
          bundle exec bin/app-identity-suite-ruby generate --stdout |
            bundle exec bin/app-identity-suite-ruby run --stdin --strict
        working-directory: ./ruby

  ruby-head-optional:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }} - ${{ matrix.os }} (optional)

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rack_1
          - rack_2
          - rack_3
        ruby:
          - head
        os:
          - ubuntu-22.04

    continue-on-error: true
    runs-on: ${{ matrix.os }}

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 #v1.245.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ./ruby

      - run: bundle exec ruby -S rake test --trace
        working-directory: ./ruby

      - run: >
          bundle exec bin/app-identity-suite-ruby generate --stdout |
            bundle exec bin/app-identity-suite-ruby run --diagnostic --stdin --strict
        working-directory: ./ruby
