name: TypeScript CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

jobs:
  typescript-ci:
    name: Typescript (Node ${{ matrix.node }}, pnpm ${{ matrix.pnpm }}) - ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
          - 18
          - 20
        pnpm:
          - 7
          - 8 # latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: ts/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: ./ts
      - run: pnpm test
        working-directory: ./ts
      - run: pnpm lint
        working-directory: ./ts
      - run: |
          pnpm format:check || {
            pnpm format
            git diff
            exit 1
          }
        working-directory: ./ts
      - run: pnpm build:all
        working-directory: ./ts
      - run: pnpm cli:generate self.json && pnpm cli:run self.json --strict
        working-directory: ./ts
