name: TypeScript CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  typescript-ci:
    name: Typescript (Node ${{ matrix.node }}, pnpm 10) - ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
        node:
          - 20
          - 22

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4.0.0
        with:
          package_json_file: ts/package.json

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: ts/pnpm-lock.yaml

      - name: Fix an uneven rollout of corepack 0.31.0 with updated keys
        run: npm install --global corepack@^0.31.0
        working-directory: ./ts

      - run: pnpm install --frozen-lockfile
        working-directory: ./ts
      - run: pnpm test
        working-directory: ./ts
      - run: pnpm check
        working-directory: ./ts

      - run: pnpm build:all
        working-directory: ./ts

      - name: Check the publint status on publishable packages
        run: |
          pnpm recursive --stream exec publint run
        working-directory: ./ts

      - name: self-test
        run: |
          pnpm --silent cli:generate --stdout |
            pnpm --silent cli:run --diagnostic --strict --stdin
        working-directory: ./ts
