name: TypeScript CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  typescript-ci:
    name: Typescript (Node ${{ matrix.node }}, pnpm 10) - ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
        node:
          - 20
          - 22

    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
        with:
          package_json_file: ts/package.json

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: ts/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: ./ts
      - run: pnpm test
        working-directory: ./ts
      - run: pnpm check
        working-directory: ./ts

      - run: pnpm build:all
        working-directory: ./ts

      - name: Check the publint status on publishable packages
        run: |
          pnpm recursive --stream exec publint run
        working-directory: ./ts

      - name: self-test
        run: |
          pnpm --silent cli:generate --stdout |
            pnpm --silent cli:run --diagnostic --strict --stdin
        working-directory: ./ts
