name: TypeScript CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  typescript-ci:
    name: Typescript (Node ${{ matrix.node }}, pnpm ${{ matrix.pnpm }}) - ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 20
        pnpm:
          - 8 # latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: ts/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: ./ts
      - run: pnpm test
        working-directory: ./ts
      - run: pnpm lint
        working-directory: ./ts

      - name: pnpm format:check
        run: |
          pnpm format:check || {
            pnpm format
            git diff
            exit 1
          }
        working-directory: ./ts

      - run: pnpm build:all
        working-directory: ./ts

      - run: pnpm exec publint
        working-directory: ./ts

      - name: self-test
        run: |
          pnpm --silent cli:generate | pnpm --silent cli:run --strict
        working-directory: ./ts
