name: TypeScript CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

jobs:
  typescript-ci:
    name: Typescript ${{ matrix.node }} (PNPM ${{ matrix.pnpm }}) - ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14
          - 16
          - 18
        pnpm:
          - 6.x.x
          - 7.x.x
          - 8.x.x # latest
        exclude:
          - os: ubuntu-latest
            pnpm: 8.x.x
            node: 14

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: ts/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: ./ts
      - run: pnpm test
        working-directory: ./ts
      - run: pnpm lint
        working-directory: ./ts
      - run: pnpm format:check
        working-directory: ./ts
      - run: pnpm build:all
        working-directory: ./ts
      - run: pnpm cli:generate self.json && pnpm cli:run self.json --strict
        working-directory: ./ts
